from collections import defaultdict

def create_frequency_tables(document, n):
    """
    Constructs a list of `n` frequency tables for an n-gram model.
    Each table[i] is a nested dict mapping each character to a dict of contexts 
    (previous i characters) and their frequencies.
    
    - Parameters:
        - document: The text document (string) used to train the model.
        - n: The value of `n` for the n-gram model (maximum n-gram length).
    - Returns:
        - A list of `n` frequency tables (list of dicts).
    """
    tables = [defaultdict(lambda: defaultdict(int)) for _ in range(n)]
    
    doc_length = len(document)
    for k in range(1, n+1): 
        table_index = k - 1 
        for i in range(doc_length - k + 1): 
            context = document[i : i + k - 1]           
            next_char = document[i + k - 1]             
            tables[table_index][next_char][context] += 1  
            
    return tables


def calculate_probability(sequence, char, tables):
    """
    Calculates the probability of a character `char` occurring immediately after 
    the given `sequence` of characters, using the precomputed frequency tables.
    
    - Parameters:
        - sequence: The preceding sequence of characters (context) as a string.
        - char: The character whose probability of occurring next is to be calculated.
        - tables: The list of frequency tables (as returned by create_frequency_tables).
    - Returns:
        - A probability value (float) for char occurring after sequence.
    """
    n = len(tables) 
    if len(sequence) >= n:
        
        context = sequence[-(n-1):] if n > 1 else ""
    else:
        context = sequence  

    while True:
        if context == "":
            total_count = 0
            for ch, ctx_dict in tables[0].items():
                total_count += ctx_dict.get("", 0)
            freq_char = tables[0].get(char, {}).get("", 0)
            return freq_char / total_count if total_count > 0 else 0.0
        
        L = len(context)  

        prev_last_char = context[-1]                        
        prev_prefix = context[:-1]                          
        freq_context = tables[L-1].get(prev_last_char, {}).get(prev_prefix, 0)
        
        if freq_context == 0:
            context = context[1:] 
            continue
        
        freq_seq_plus_char = 0
        if L < len(tables): 
            freq_seq_plus_char = tables[L].get(char, {}).get(context, 0)
        
        return freq_seq_plus_char / freq_context

def predict_next_char(sequence, tables, vocabulary):
    """
    Predicts the most likely next character based on the given input `sequence` of characters.
    
    - Parameters:
        - sequence: The input sequence (context) used to predict the next character.
        - tables: The list of frequency tables generated by the n-gram model.
        - vocabulary: The set of possible characters (all characters seen in training).
    - Returns:
        - The character (string of length 1) with the highest conditional probability of occurring next.
    """
    best_char = None
    best_prob = -1.0  
    
    for candidate in vocabulary:
        prob = calculate_probability(sequence, candidate, tables)
        if prob > best_prob:
            best_prob = prob
            best_char = candidate
    
    return best_char if best_char is not None else ''
