def create_frequency_tables(document, n):
    """
    Create frequency tables for 1-gram through n-gram sequences in the document.
    
    Args:
        document (str): The text corpus to learn from.
        n (int): The maximum length of n-grams to consider.
    Returns:
        dict: A dictionary where keys 1..n map to another dict of n-gram counts.
              e.g., tables[2]['th'] = count of "th" in document.
    """
    tables = [{} for _ in range(n)]
    lenght = len(document)
    
    for i in range(lenght):
        for gram_len in range(1, n + 1):
            if i + gram_len <= lenght:
                seq = document[i:i + gram_len]
                table = tables[gram_len - 1]
                table[seq] = table.get(seq, 0) + 1
    return tables


def calculate_probability(sequence, char, tables):
    """
    Calculate the probability of `char` occurring after `sequence` using the n-gram tables.
    
    Args:
        sequence (str): The preceding sequence of characters (context).
        char (str): The character whose probability we want to find as the next character.
        tables (dict): Frequency tables generated by create_frequency_tables.
    Returns:
        float: The probability P(char | sequence).
    """
    n = len(tables)
    context_len = min(len(sequence), n - 1)
    context = sequence[-context_len:] if context_len > 0 else ""
    
    if context == "":
        # Index into unigram table
        count_tot = sum(tables[0].values())
        count_char = tables[0].get(char, 0)
        return count_char / count_tot if count_tot > 0 else 0.0
    else:
        # Index into bigram or trigram table correctly
        prefix_table = tables[context_len - 1]  # length of context
        full_table = tables[context_len]        # context + char
        seq_count = prefix_table.get(context, 0)
        seq_char_count = full_table.get(context + char, 0)
        return seq_char_count / seq_count if seq_count > 0 else 0.0

def predict_next_char(sequence, tables, vocabulary):
    """
    Predict the most likely next character given the current sequence.
    
    Args:
        sequence (str): The current input sequence (context).
        tables (dict): Frequency tables of n-grams (from create_frequency_tables).
        vocabulary (iterable): Collection of all possible characters to consider.
    Returns:
        str: The predicted next character (the one with highest conditional probability).
    """
    best_char = None
    best_prob = -1.0
    # Loop through all characters in the vocabulary to find the highest P(char | sequence)
    for char in vocabulary:
        prob = calculate_probability(sequence, char, tables)
        if prob > best_prob:
            best_prob = prob
            best_char = char
    return best_char if best_char is not None else ""